#!/usr/bin/env python3
"""constraints/mutation.lock must satisfy constraints/mutation.in.

Every other lock is regenerated by scripts/regenerate-locks.sh, which the
ci.yml `lock` gate runs on every pull request before asserting a clean
``git diff``. That gate is what stops an input from drifting away from
its lock.

``constraints/mutation.lock`` is deliberately NOT regenerated there:
mutmut and glob2 publish no wheels, so resolving that graph would build
their sdists and execute third-party ``setup.py`` code on every PR. It
is regenerated by hand via ``scripts/regenerate-mutation-lock.sh``.

That exclusion left a hole. Editing the ``mutmut==`` pin in
``mutation.in`` without running the manual script passes every check:
the routine script skips the lock, so the diff stays clean, and
``mutation.yml`` installs the lock rather than reading the input. The
weekly mutation run would silently keep using the old version.

This check closes it WITHOUT resolving anything. It only reads the two
files and compares pins, so it executes no build code and is safe to run
on every pull request — which is the whole point.

Usage:
    python scripts/check_mutation_lock_sync.py     # check; exit 1 on drift

Stdlib only, matching scripts/check_versions.py and
scripts/check_precommit_lockstep.py, so it runs as a ``pre-commit``
``language: system`` hook with no env bootstrap.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "constraints" / "mutation.in"
LOCK = ROOT / "constraints" / "mutation.lock"

REGEN = "scripts/regenerate-mutation-lock.sh"

# `name==version`, the only form this checker can verify without resolving.
PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;#]+)\s*$")


def _normalize(name: str) -> str:
    """PEP 503 normalized distribution name.

    uv may emit a different spelling than the input uses (``junit-xml``
    vs ``junit_xml``), so compare normalized forms rather than raw text.
    """
    return re.sub(r"[-_.]+", "-", name).lower()


def _read_input_pins(text: str) -> tuple[dict[str, str], list[str]]:
    """Parse ``mutation.in`` into {normalized name: version}.

    Returns the pins plus any lines this checker cannot verify, so an
    unsupported requirement form fails loudly instead of being skipped.
    """
    pins: dict[str, str] = {}
    unverifiable: list[str] = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        match = PIN.match(line)
        if match is None:
            unverifiable.append(line)
            continue
        pins[_normalize(match.group(1))] = match.group(2)
    return pins, unverifiable


def _read_lock_pins(text: str) -> dict[str, str]:
    """Parse ``mutation.lock`` into {normalized name: version}.

    uv emits ``name==version \\`` followed by indented ``--hash`` lines,
    so anchoring to the start of a line means a hash continuation can
    never be mistaken for a pin.
    """
    return {
        _normalize(m.group(1)): m.group(2)
        for m in re.finditer(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==(\S+?)(?:\s|$)", text, re.MULTILINE)
    }


def main() -> int:
    if not INPUT.exists() or not LOCK.exists():
        print(f"error: expected both {INPUT} and {LOCK} to exist", file=sys.stderr)
        return 1

    wanted, unverifiable = _read_input_pins(INPUT.read_text(encoding="utf-8"))
    have = _read_lock_pins(LOCK.read_text(encoding="utf-8"))

    if unverifiable:
        print(
            f"error: {INPUT.relative_to(ROOT)} contains requirement forms this "
            f"check cannot verify without resolving:",
            file=sys.stderr,
        )
        for line in unverifiable:
            print(f"    {line}", file=sys.stderr)
        print(
            "\nOnly exact `name==version` pins can be compared against the lock "
            f"without building sdists. Either pin exactly, or extend {Path(__file__).name}.",
            file=sys.stderr,
        )
        return 1

    if not wanted:
        print(f"error: no pins found in {INPUT.relative_to(ROOT)}", file=sys.stderr)
        return 1
    if not have:
        print(f"error: no pins found in {LOCK.relative_to(ROOT)}", file=sys.stderr)
        return 1

    drift = []
    for name, version in sorted(wanted.items()):
        actual = have.get(name)
        if actual is None:
            drift.append(f"  {name}: pinned to {version} in the input, ABSENT from the lock")
        elif actual != version:
            drift.append(f"  {name}: input wants {version}, lock pins {actual}")

    if drift:
        print(
            f"{LOCK.relative_to(ROOT)} is out of sync with {INPUT.relative_to(ROOT)}.\n",
            file=sys.stderr,
        )
        print("\n".join(drift), file=sys.stderr)
        print(
            f"\nThis lock is excluded from scripts/regenerate-locks.sh on purpose "
            f"(resolving it builds sdists), so the routine gate cannot catch this.\n"
            f"Regenerate it deliberately:\n"
            f"    python -m pip install --require-hashes -r constraints/uv-bootstrap.lock\n"
            f"    {REGEN}",
            file=sys.stderr,
        )
        return 1

    names = ", ".join(f"{n}=={v}" for n, v in sorted(wanted.items()))
    print(f"{LOCK.relative_to(ROOT)} satisfies {INPUT.relative_to(ROOT)} ({names})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
